config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/', to: 'customers#index', as: 'root'
  get '/customers/missing_email', to: 'customers#missing_email', as: 'missing_email_customers'
  get '/customers/alphabetized', to: 'customers#alphabetized', as: 'alphabetized_customers'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, presence: true
  validates :email, uniqueness: { allow_nil: true, allow_blank: true }
  
  has_one_attached :image

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "full_name", "id", "id_value", "notes", "phone_number", "updated_at"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email: [nil, ''])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="column is-4">
  <div class="card">
    <div class="card-image">
      <figure class="image is-4by3">
        <%= image_tag customer.image, class: "customer-image" if customer.image.attached? %>
      </figure>
    </div>
    <div class="card-content">

      <div class="content">
        <p class="title is-4">
          <%= customer.full_name%>
        </p>
        <p><strong>Email:</strong> <%= customer.email%></p>
        <p><strong>Phone Number:</strong> <%= customer.phone_number%></p>
        <p><strong>Notes:</strong> <%= customer.notes%></p>
      </div>
    </div>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<div class="mt-6 mx-6">
  <%= link_to "All Customers", root_path, class: "button is-primary" %>
  <%= link_to "Missing Email Customers", missing_email_customers_path, class: "button is-primary" %>
  <div class="columns is-multiline is-2 mt-6">
    <% @customers.each do |customer|%>
      <%= render partial: 'customers/customer', locals: { customer: customer } %>
    <% end %>
  </div>
</div>

app/views/customers/index.html.erb
<div class="mt-6 mx-6">
  <%= link_to "Missing Email Customers", missing_email_customers_path, class: "button is-primary" %>
  <%= link_to "Alphabetized Customers", alphabetized_customers_path, class: "button is-primary" %>
  <div class="columns is-multiline is-2 mt-6">
    <% @customers.each do |customer|%>
      <%= render partial: 'customers/customer', locals: { customer: customer } %>
    <% end %>
  </div>
</div>

app/views/customers/missing_email.html.erb
<div class="mt-6 mx-6">
  <%= link_to "All Customers", root_path, class: "button is-primary" %>
  <%= link_to "Alphabetized Customers", alphabetized_customers_path, class: "button is-primary" %>
  <div class="columns is-multiline is-2 mt-6">
    <% @customers.each do |customer|%>
      <%= render partial: 'customers/customer', locals: { customer: customer } %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>